-- Hybrid Plan Phase 14: Work Clustering Match Candidate Table
-- Holds candidate pairs generated by the deterministic clustering rules.
-- Rules 7, 8, 11, 12 (cross-language, ambiguous creator/anonymous,
-- date/edition conflict, creator identity uncertain) and 13 (free translation
-- without an explicit designator) produce candidates that require human review.
-- Rules 9 and 10 (adaptation, work_type mismatch) are hard blocks and never
-- enter the queue.

-- relationship_type classifies the pair and drives the merge gate:
--   translation    - same Work, different language Expression -> merge
--   edition        - same Work, different Expression (edition)  -> merge
--   adaptation     - different Work based on another Work        -> do not merge
--   freetranslation- creative/free translation forms a new Work   -> do not merge,
--                    link via freelyTranslatedFrom/freelyTranslatedAs instead
--   unknown        - no relationship classification yet           -> human review
CREATE TABLE IF NOT EXISTS work_match_candidates (
    id                  BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    resource_a_id       BIGINT UNSIGNED NOT NULL,  -- FK to record_resources
    resource_b_id       BIGINT UNSIGNED NOT NULL,
    match_tier          TINYINT NOT NULL,          -- tier that generated this candidate

    relationship_type   ENUM('translation','edition','adaptation','freetranslation','unknown')
                           DEFAULT 'unknown',
    work_type_a         VARCHAR(32),               -- 'serial' | 'monograph'
    work_type_b         VARCHAR(32),

    match_evidence      JSON,                      -- title/creator/language/date/edition comparison

    status              ENUM('pending','accepted','rejected','skipped','reverted')
                           DEFAULT 'pending',
    review_note         VARCHAR(1024),
    reviewed_by         VARCHAR(128),
    reviewed_at         TIMESTAMP NULL,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Reversal (un-merge) support
    reverted_from       BIGINT UNSIGNED NULL,      -- FK to the merged work_match_candidates.id
    work_snapshot       JSON,                      -- prior separate-Work state for restore

    -- Optional, for the future LLM original-title suggestion tier.
    -- Never authoritative; only evidence shown to the reviewer.
    suggested_original_title   VARCHAR(1024) NULL,
    suggested_title_confidence DECIMAL(4,3)  NULL,

    UNIQUE KEY (resource_a_id, resource_b_id),
    KEY (status),
    KEY (created_at),
    KEY (relationship_type),

    CONSTRAINT fk_wmc_a FOREIGN KEY (resource_a_id) REFERENCES record_resources(id) ON DELETE CASCADE,
    CONSTRAINT fk_wmc_b FOREIGN KEY (resource_b_id) REFERENCES record_resources(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;